[python crash] 20250915 105449.log - 檔案名稱: Protected by Curtain-e-locker]
Python 版本: 3.11.3 | 1 packaged by Anaconda, Inc. | (main, Apr 19 2023, 23:46:34) [MSC v.1916 64 bit (AMD64)]
執行緒: Standard Python

Windows fatal exception: code 0x80000003

Thread 0x00000638 (most recent call first):
File "C:\ProgramData\anaconda3\Lib\threading.py", line 324 in wait
File "C:\ProgramData\anaconda3\Lib\threading.py", line 622 in wait
File "C:\ProgramData\anaconda3\Lib\threading.py", line 1038 in _bootstrap_inner
File "C:\ProgramData\anaconda3\Lib\threading.py", line 995 in _bootstrap

Current thread 0x00000684 (most recent call first):
Garbage-collecting
File "C:\ProgramData\anaconda3\Lib\xml\etree\ElementTree.py", line 1709 in feed
File "C:\ProgramData\anaconda3\Lib\xml\etree\ElementTree.py", line 1292 in iterator
File "C:\Users\Kccheng\AppData\Roaming\Python\Python311\site-packages\openpyxl\worksheet\_reader.py", line 178 in parse_dimensions
File "C:\Users\Kccheng\AppData\Roaming\Python\Python311\site-packages\openpyxl\worksheet\_reader.py", line 42 in __init__
File "C:\Users\Kccheng\AppData\Roaming\Python\Python311\site-packages\openpyxl\worksheet\_reader.py", line 228 in read_only
File "C:\Users\Kccheng\AppData\Roaming\Python\Python311\site-packages\openpyxl\reader\excel.py", line 303 in read_worksheets
File "C:\Users\Kccheng\AppData\Roaming\Python\Python311\site-packages\openpyxl\reader\excel.py", line 348 in load_workbook
File "C:\Prodi\Kccheng\watchdog_monitoring_v2\core\excel_parser.py", line 295 in safe_load_workbook
File "C:\Prodi\Kccheng\watchdog_monitoring_v2\core\watchdog_monitoring_v2_core.py", line 309 in dump_excel_cell_with_timeout
File "C:\Prodi\Kccheng\watchdog_monitoring_v2\core\watchdog_monitoring_v2_core.py", line 314 in compare_excel_changes
File "C:\Prodi\Kccheng\watchdog_monitoring_v2\core\watchdog_monitoring_v2_core.py", line 413 in lambda>
File "C:\ProgramData\anaconda3\Lib\concurrent\futures\thread.py", line 37 in run
File "C:\ProgramData\anaconda3\Lib\concurrent\futures\thread.py", line 58 in _worker
File "C:\ProgramData\anaconda3\Lib\threading.py", line 1038 in _bootstrap_inner
File "C:\ProgramData\anaconda3\Lib\threading.py", line 995 in _bootstrap

Thread 0x00006558 (most recent call first):
File "C:\ProgramData\anaconda3\Lib\concurrent\futures\thread.py", line 81 in _worker
File "C:\ProgramData\anaconda3\Lib\threading.py", line 975 in run
File "C:\ProgramData\anaconda3\Lib\threading.py", line 1038 in _bootstrap_inner
File "C:\ProgramData\anaconda3\Lib\threading.py", line 995 in _bootstrap

Thread 0x00006294 (most recent call first):
File "C:\Users\Kccheng\AppData\Roaming\Python\Python311\site-packages\openpyxl\descriptors\sequence.py", line 72 in __set__
File "C:\Users\Kccheng\AppData\Roaming\Python\Python311\site-packages\openpyxl\workbook\external_link\external.py", line 77 in __init__
File "C:\Users\Kccheng\AppData\Roaming\Python\Python311\site-packages\openpyxl\workbook\external_link\external.py", line 99 in __
